#!/usr/bin/env bash
set -euo pipefail

# Run integration tests against a running server
# Usage: ./scripts/test-integration.sh [local|compose]

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(dirname "$SCRIPT_DIR")"

cd "$ROOT_DIR"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Parse arguments
MODE="${1:-local}"
shift || true

cleanup() {
  echo -e "${YELLOW}Cleaning up...${NC}"
  ./scripts/stop-all.sh 2>/dev/null || true
}

wait_for_server() {
  local url="$1"
  local max_attempts=30
  local attempt=1

  echo -e "${YELLOW}Waiting for server at $url...${NC}"
  while [ $attempt -le $max_attempts ]; do
    if curl -s "$url/health" > /dev/null 2>&1; then
      echo -e "${GREEN}Server is ready!${NC}"
      return 0
    fi
    echo "Attempt $attempt/$max_attempts..."
    sleep 2
    attempt=$((attempt + 1))
  done

  echo -e "${RED}Server failed to start within timeout${NC}"
  return 1
}

case "$MODE" in
  local|l)
    echo -e "${GREEN}Running integration tests in LOCAL mode (E2E with test server)${NC}"

    # Stop any running services to avoid port conflicts
    cleanup

    # Build if needed
    if [ ! -d "node/packages/service/moronlist/dist" ]; then
      echo "Building project..."
      ./scripts/build.sh --no-format
    fi

    TEST_EXIT_CODE=0

    # Test MoronList (self-contained: spins up its own server)
    echo -e "${GREEN}Running MoronList tests...${NC}"
    cd node/packages/service/moronlist
    npm test || TEST_EXIT_CODE=$?
    cd "$ROOT_DIR"

    exit $TEST_EXIT_CODE
    ;;

  compose|c)
    echo -e "${GREEN}Running integration tests against DOCKER COMPOSE${NC}"

    # Stop any running services
    cleanup

    # Create host data directory for docker compose
    TEST_DIR="$ROOT_DIR/.tests/compose-test-$(date +%s)"
    HOST_DATA_DIR="$TEST_DIR/data"
    mkdir -p "$HOST_DATA_DIR/moronlist/db" "$HOST_DATA_DIR/moronlist/logs" \
             "$HOST_DATA_DIR/persona/db" "$HOST_DATA_DIR/persona/logs"

    # Create temporary env file for docker-compose (test configuration)
    TEST_ENV_FILE="$TEST_DIR/.env.test"
    cat > "$TEST_ENV_FILE" << EOF
# Test environment - auto-generated by test-integration.sh
NODE_ENV=test

# Persona auth secrets (shared across all services)
PERSONA_JWT_SECRET=test-jwt-secret-for-integration-tests
PERSONA_SESSION_SECRET=test-session-secret-for-integration-tests
PERSONA_INTERNAL_SECRET=test-internal-secret-for-integration-tests

# Persona server config
PERSONA_GOOGLE_CLIENT_ID=test-google-client-id
PERSONA_GOOGLE_CLIENT_SECRET=test-google-client-secret

# Service URLs
MORONLIST_PUBLIC_URL=http://localhost:4000
EOF

    # Export for docker-compose (volume mounts and env file)
    export MORONLIST_DATA_HOST_DIR="$HOST_DATA_DIR/moronlist/db"
    export MORONLIST_LOG_HOST_DIR="$HOST_DATA_DIR/moronlist/logs"
    export PERSONA_DATA_HOST_DIR="$HOST_DATA_DIR/persona/db"
    export PERSONA_LOG_HOST_DIR="$HOST_DATA_DIR/persona/logs"
    export ENV_FILE="$TEST_ENV_FILE"

    # Export secrets for test runner (must match values in .env.test)
    export PERSONA_JWT_SECRET="test-jwt-secret-for-integration-tests"
    export PERSONA_INTERNAL_SECRET="test-internal-secret-for-integration-tests"

    # Export for test runner (runs on host, needs host paths)
    export MORONLIST_DATA_DIR="$HOST_DATA_DIR/moronlist/db"
    export MORONLIST_LOG_FILE_DIR="$HOST_DATA_DIR/moronlist/logs"

    TEST_EXIT_CODE=0

    # Docker compose command
    COMPOSE_CMD="docker compose -f production/docker-compose.yml"

    # Run migrations
    echo "Running MoronList migrations..."
    $COMPOSE_CMD run --rm moronlist-migrations

    # Start MoronList server
    echo "Starting MoronList server..."
    $COMPOSE_CMD up -d moronlist-server

    if ! wait_for_server "http://localhost:4000"; then
      echo "MoronList server failed to start. Showing logs:"
      $COMPOSE_CMD logs moronlist-migrations
      $COMPOSE_CMD logs moronlist-server
      $COMPOSE_CMD down
      rm -rf "$TEST_DIR"
      exit 1
    fi

    echo -e "${GREEN}Running MoronList tests...${NC}"
    export TEST_URL="http://localhost:4000"
    export TEST_DB_PATH="$HOST_DATA_DIR/moronlist/db/moronlist.db"
    cd node/packages/service/moronlist
    npm test || TEST_EXIT_CODE=$?
    cd "$ROOT_DIR"

    # Cleanup
    $COMPOSE_CMD down
    rm -rf "$TEST_DIR"

    exit ${TEST_EXIT_CODE:-0}
    ;;

  *)
    echo "Usage: $0 [local|compose]"
    echo "  local           - Run tests against local Node.js server"
    echo "  compose         - Run tests against Docker Compose setup"
    exit 1
    ;;
esac
